### PR TITLE
Added hook for overriding output of HasAvailablePerksToAssign()

### LINKED ISSUE #33: Allow overriding of HasAvailablePerksToAssign() output
XComGameState_Unit currently has an exception for Psi Operatives in HasAvailablePerksToAssign() that prevents the player from choosing a perk for every rank a soldier has reached. It would be ideal for mods to be capable of extending this behavior to other classes.

### PR DESCRIPTION
**Pull request by BTernaryTau**
Resolves #33.

### CODE REVIEW

**Comment by MalucoMarinero** [comment]
Cheers @BTernaryTau, this looks like it will maintain compatibility just reading it, have you tested it on build with Vanilla? (with psi operatives still working as expected?)

**Comment by BTernaryTau** [comment]
I haven't tested it yet. Is there anything special I have to do when testing a highlander?

**Comment by robojumper** [comment]
Looks good to me, the function is used by UI only so it won't cause issues in the strategy start state etc.

**Comment by BTernaryTau** [comment]
Closing this and opening an updated pull request.

**Pull request closed without merging**
